export const CREATE_ROOM = "CREATE_ROOM"
export const ADD_ALL_MESSAGES = "ADD_ALL_MESSAGES"
export const APPEND_NEW_MESSAGE = "APPEND_NEW_MESSAGE"
export const RESET_ALL_MESSAGES = "RESET_ALL_MESSAGES"
